version: 0.2
env:
  parameter-store:
    secret: password

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo "Install Dependencies" | npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws cloudformation package
        --template-file template.yml
        --s3-bucket $BUCKET
        --output-template-file outputtemplate.yml

artifacts:
  type: zip
  files:
    - outputtemplate.yml
