version=0.1

[default.deploy]
region = "us-east-1"
confirm_changeset = false

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
stack_name = "dev-sam-starter-ts"
s3_bucket = "dev-sam-starter-ts"
parameter_overrides = [
  "EnvType=dev",
  "GithubBranchSource=develop",
  "GithubBranchDest=main",
  "GithubOAuthToken="
]

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
stack_name = "prod-sam-starter-ts"
s3_bucket = "prod-sam-starter-ts"
parameter_overrides = [
  "EnvType=prod",
  "GithubBranchSource=main",
  "GithubOAuthToken="
]
